* ============================================================
* t_embed.asm — EMBED test harness
* ============================================================
* 6 tests for EMBED wrapping arithmetic semantics.
* Per-test reporting via result bitmap at $1704 (1 byte, 6 bits used).
* Dependencies: equates.inc, macros.inc, fxmath.asm, vecop.asm
* Vectors: tables/embed_vectors.asm (generated by gen_embed_vectors.py)
* ============================================================

                INCLUDE include/equates.inc
                INCLUDE include/macros.inc
                INCLUDE include/fxmath.inc

                ORG     $0600

* -------- Entry point --------
START:
                ORCC    #$50
                LDMD    #1
                LDS     #STACK_TOP
                JSR     CLEAR_SCREEN
                JSR     RUN_TESTS
                JSR     DISPLAY_RESULTS
HALT:           BRA     HALT

* -------- Scratch RAM --------
PASS_CNT        EQU     $1700
FAIL_CNT        EQU     $1702
RESULT_BITS     EQU     $1704
LAST_FAIL_ID    EQU     $1705
CUR_TEST_ID     EQU     $1706
DEC_BUF         EQU     $1730
DEC_DTEMP       EQU     $1736
DEC_SCRPTR      EQU     $1738

* -------- Test data buffers --------
TOK_BUF         EQU     $1760
TKEMB_BUF       EQU     $1780
PSEMB_BUF       EQU     $18C0
OUT_BUF         EQU     $19C0

* ============================================================
* RUN_TESTS
* ============================================================
RUN_TESTS:
                CLRA
                CLRB
                STD     PASS_CNT
                STD     FAIL_CNT
                CLR     RESULT_BITS
                LDA     #$FF
                STA     LAST_FAIL_ID

                JSR     TEST_0
                JSR     TEST_1
                JSR     TEST_2
                JSR     TEST_3
                JSR     TEST_4
                JSR     TEST_5
                RTS

* ============================================================
* Framework helpers
* ============================================================
LOAD_BUF:
                CMPW    #0
                BEQ     LB_EXIT
LB_LOOP:
                LDD     ,X++
                STD     ,Y++
                DECW
                BNE     LB_LOOP
LB_EXIT:
                RTS

RECORD_PASS:
                LDD     PASS_CNT
                ADDD    #1
                STD     PASS_CNT
                LDA     CUR_TEST_ID
                LDB     #1
RP_SHIFT:
                TSTA
                BEQ     RP_DONE
                LSLB
                DECA
                BRA     RP_SHIFT
RP_DONE:
                ORB     RESULT_BITS
                STB     RESULT_BITS
                RTS

RECORD_FAIL:
                LDD     FAIL_CNT
                ADDD    #1
                STD     FAIL_CNT
                LDA     CUR_TEST_ID
                STA     LAST_FAIL_ID
                RTS

* ============================================================
* Test 0: EMBED_SINGLE_TOKEN
* ============================================================
TEST_0:
                CLR     CUR_TEST_ID
                LDX     #TOK_0
                LDY     #TOK_BUF
                LDW     SEQ_0
                JSR     LOAD_BUF
                LDX     #TKEMB_0
                LDY     #TKEMB_BUF
                LDW     TKEMB_CNT_0
                JSR     LOAD_BUF
                LDX     #PSEMB_0
                LDY     #PSEMB_BUF
                LDW     CNT_0
                JSR     LOAD_BUF
                LDD     #TOK_BUF
                STD     EM_TOK
                LDD     #TKEMB_BUF
                STD     EM_TKE
                LDD     #PSEMB_BUF
                STD     EM_PSE
                LDD     #OUT_BUF
                STD     EM_OUT
                LDD     SEQ_0
                STD     EM_SEQ
                LDD     DIM_0
                STD     EM_DIM
                JSR     EMBED
                LDX     #OUT_BUF
                LDY     #EXPECT_0
                LDW     CNT_0
T0_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T0_FAIL
                DECW
                BNE     T0_CHK
                JSR     RECORD_PASS
                RTS
T0_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 1: EMBED_SEQ2
* ============================================================
TEST_1:
                LDA     #1
                STA     CUR_TEST_ID
                LDX     #TOK_1
                LDY     #TOK_BUF
                LDW     SEQ_1
                JSR     LOAD_BUF
                LDX     #TKEMB_1
                LDY     #TKEMB_BUF
                LDW     TKEMB_CNT_1
                JSR     LOAD_BUF
                LDX     #PSEMB_1
                LDY     #PSEMB_BUF
                LDW     CNT_1
                JSR     LOAD_BUF
                LDD     #TOK_BUF
                STD     EM_TOK
                LDD     #TKEMB_BUF
                STD     EM_TKE
                LDD     #PSEMB_BUF
                STD     EM_PSE
                LDD     #OUT_BUF
                STD     EM_OUT
                LDD     SEQ_1
                STD     EM_SEQ
                LDD     DIM_1
                STD     EM_DIM
                JSR     EMBED
                LDX     #OUT_BUF
                LDY     #EXPECT_1
                LDW     CNT_1
T1_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T1_FAIL
                DECW
                BNE     T1_CHK
                JSR     RECORD_PASS
                RTS
T1_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 2: EMBED_MAX_SEQ (SEQ=8, DIM=16, 128 outputs)
* ============================================================
TEST_2:
                LDA     #2
                STA     CUR_TEST_ID
                LDX     #TOK_2
                LDY     #TOK_BUF
                LDW     SEQ_2
                JSR     LOAD_BUF
                LDX     #TKEMB_2
                LDY     #TKEMB_BUF
                LDW     TKEMB_CNT_2
                JSR     LOAD_BUF
                LDX     #PSEMB_2
                LDY     #PSEMB_BUF
                LDW     CNT_2
                JSR     LOAD_BUF
                LDD     #TOK_BUF
                STD     EM_TOK
                LDD     #TKEMB_BUF
                STD     EM_TKE
                LDD     #PSEMB_BUF
                STD     EM_PSE
                LDD     #OUT_BUF
                STD     EM_OUT
                LDD     SEQ_2
                STD     EM_SEQ
                LDD     DIM_2
                STD     EM_DIM
                JSR     EMBED
                LDX     #OUT_BUF
                LDY     #EXPECT_2
                LDW     CNT_2
T2_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T2_FAIL
                DECW
                BNE     T2_CHK
                JSR     RECORD_PASS
                RTS
T2_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 3: EMBED_TOKEN_ZERO — both positions use token 0
* ============================================================
TEST_3:
                LDA     #3
                STA     CUR_TEST_ID
                LDX     #TOK_3
                LDY     #TOK_BUF
                LDW     SEQ_3
                JSR     LOAD_BUF
                LDX     #TKEMB_3
                LDY     #TKEMB_BUF
                LDW     TKEMB_CNT_3
                JSR     LOAD_BUF
                LDX     #PSEMB_3
                LDY     #PSEMB_BUF
                LDW     CNT_3
                JSR     LOAD_BUF
                LDD     #TOK_BUF
                STD     EM_TOK
                LDD     #TKEMB_BUF
                STD     EM_TKE
                LDD     #PSEMB_BUF
                STD     EM_PSE
                LDD     #OUT_BUF
                STD     EM_OUT
                LDD     SEQ_3
                STD     EM_SEQ
                LDD     DIM_3
                STD     EM_DIM
                JSR     EMBED
                LDX     #OUT_BUF
                LDY     #EXPECT_3
                LDW     CNT_3
T3_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T3_FAIL
                DECW
                BNE     T3_CHK
                JSR     RECORD_PASS
                RTS
T3_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 4: EMBED_TOKEN_MAX — token=9 (last valid row)
* ============================================================
TEST_4:
                LDA     #4
                STA     CUR_TEST_ID
                LDX     #TOK_4
                LDY     #TOK_BUF
                LDW     SEQ_4
                JSR     LOAD_BUF
                LDX     #TKEMB_4
                LDY     #TKEMB_BUF
                LDW     TKEMB_CNT_4
                JSR     LOAD_BUF
                LDX     #PSEMB_4
                LDY     #PSEMB_BUF
                LDW     CNT_4
                JSR     LOAD_BUF
                LDD     #TOK_BUF
                STD     EM_TOK
                LDD     #TKEMB_BUF
                STD     EM_TKE
                LDD     #PSEMB_BUF
                STD     EM_PSE
                LDD     #OUT_BUF
                STD     EM_OUT
                LDD     SEQ_4
                STD     EM_SEQ
                LDD     DIM_4
                STD     EM_DIM
                JSR     EMBED
                LDX     #OUT_BUF
                LDY     #EXPECT_4
                LDW     CNT_4
T4_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T4_FAIL
                DECW
                BNE     T4_CHK
                JSR     RECORD_PASS
                RTS
T4_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 5: EMBED_WRAP — divergence test
* Expected OUT_BUF[0] = -25536 ($9C40). Clamp would be 32767 ($7FFF).
* ============================================================
TEST_5:
                LDA     #5
                STA     CUR_TEST_ID
                LDX     #TOK_5
                LDY     #TOK_BUF
                LDW     SEQ_5
                JSR     LOAD_BUF
                LDX     #TKEMB_5
                LDY     #TKEMB_BUF
                LDW     TKEMB_CNT_5
                JSR     LOAD_BUF
                LDX     #PSEMB_5
                LDY     #PSEMB_BUF
                LDW     CNT_5
                JSR     LOAD_BUF
                LDD     #TOK_BUF
                STD     EM_TOK
                LDD     #TKEMB_BUF
                STD     EM_TKE
                LDD     #PSEMB_BUF
                STD     EM_PSE
                LDD     #OUT_BUF
                STD     EM_OUT
                LDD     SEQ_5
                STD     EM_SEQ
                LDD     DIM_5
                STD     EM_DIM
                JSR     EMBED
                LDX     #OUT_BUF
                LDY     #EXPECT_5
                LDW     CNT_5
T5_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T5_FAIL
                DECW
                BNE     T5_CHK
                JSR     RECORD_PASS
                RTS
T5_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Display helpers
* ============================================================
CLEAR_SCREEN:
                LDA     #$20
                STA     SCREEN
                LDX     #SCREEN
                LDU     #SCREEN+1
                LDW     #511
                TFM     X+,U+
                RTS

DISPLAY_RESULTS:
                LDX     #SCREEN
                LDU     #LBL_PASS
                JSR     COPY_STRING
                LDD     PASS_CNT
                JSR     WRITE_DECIMAL_4
                LDU     #LBL_MID
                JSR     COPY_STRING
                LDD     FAIL_CNT
                JSR     WRITE_DECIMAL_4
                LDX     #SCREEN+32
                LDU     #LBL_BITS
                JSR     COPY_STRING
                CLRA
                LDB     RESULT_BITS
                JSR     WRITE_HEX_4
                LDU     #LBL_LF
                JSR     COPY_STRING
                CLRA
                LDB     LAST_FAIL_ID
                JSR     WRITE_HEX_4
                LDX     #SCREEN+64
                LDU     #LBL_DONE
                JSR     COPY_STRING
                RTS

COPY_STRING:
                LDA     ,U+
                BEQ     CS_DONE
                STA     ,X+
                BRA     COPY_STRING
CS_DONE:        RTS

WRITE_DECIMAL_4:
                STX     DEC_SCRPTR
                LDU     #DEC_BUF
                LDX     #DIV_TABLE
                JSR     WD4_DIGIT
                JSR     WD4_DIGIT
                JSR     WD4_DIGIT
                ADDB    #$30
                STB     ,U
                LDX     DEC_SCRPTR
                LDD     DEC_BUF
                STD     ,X++
                LDD     DEC_BUF+2
                STD     ,X++
                RTS

WD4_DIGIT:
                LDY     ,X++
                STY     DEC_DTEMP
                LDY     #$002F
WD4_LOOP:
                LEAY    1,Y
                SUBD    DEC_DTEMP
                BCC     WD4_LOOP
                ADDD    DEC_DTEMP
                PSHS    D
                TFR     Y,D
                STB     ,U+
                PULS    D
                RTS

WRITE_HEX_4:
                PSHS    D
                LDA     ,S
                JSR     WHEX_BYTE
                LDA     1,S
                JSR     WHEX_BYTE
                LEAS    2,S
                RTS

WHEX_BYTE:
                PSHS    A
                LSRA
                LSRA
                LSRA
                LSRA
                JSR     WHEX_NIB
                PULS    A
                ANDA    #$0F
                JSR     WHEX_NIB
                RTS

WHEX_NIB:
                CMPA    #10
                BLT     WHEX_D
                ADDA    #'A-10
                BRA     WHEX_OUT
WHEX_D:
                ADDA    #'0
WHEX_OUT:
                STA     ,X+
                RTS

DIV_TABLE:      FDB     1000
                FDB     100
                FDB     10

LBL_PASS:       FCC     "EMB: P="
                FCB     0
LBL_MID:        FCC     " F="
                FCB     0
LBL_BITS:       FCC     "B="
                FCB     0
LBL_LF:         FCC     " LF="
                FCB     0
LBL_DONE:       FCC     "DONE"
                FCB     0

                INCLUDE src/fxmath.asm
                INCLUDE src/vecop.asm

                INCLUDE tables/embed_vectors.asm

                END     START
