* ============================================================
* t_fxmath.asm — FXMATH test harness
* ============================================================
* Loads vectors.bin, runs each multiply test, counts PASS/FAIL
* per routine, displays split counters on screen at $0400.
* Captures diagnostic data for debugging.
* Dependencies: equates.inc, macros.inc, fxmath.inc, fxmath.asm
* Inputs: test/vectors.bin (generated by tables/ref_attn11.py)
* ============================================================

                INCLUDE include/equates.inc
                INCLUDE include/macros.inc
                INCLUDE include/fxmath.inc

                ORG     $0200

* -------- Entry point --------
START:
                ORCC    #$50            ; mask IRQ and FIRQ
                LDS     #STACK_TOP
                JSR     CLEAR_SCREEN
                JSR     RUN_TESTS
                JSR     DISPLAY_RESULTS
HALT:           BRA     HALT            ; spin forever

* -------- Scratch RAM (below string area at $1800, safe) --------
PASS_M8         EQU     $1700           ; 2 bytes: MUL8Q15 passes
FAIL_M8         EQU     $1702           ; 2 bytes: MUL8Q15 fails
PASS_M15        EQU     $1704           ; 2 bytes: MUL15Q15 passes
FAIL_M15        EQU     $1706           ; 2 bytes: MUL15Q15 fails
LOOP_CNT        EQU     $1708           ; 2 bytes: test loop counter
* ---- Diagnostic: first MUL15Q15 record capture ----
DIAG_M15        EQU     $1710           ; 8 bytes: a[2] b[2] exp[2] act[2]
DIAG_M15_DONE   EQU     $1718           ; 1 byte: flag
DIAG_TEMP       EQU     $1719           ; 2 bytes: temp for saving D
* ---- Diagnostic: X register captures ----
DIAG_X_AT_M15   EQU     $171C           ; 2 bytes: X at top of M15_LOOP
DIAG_X_CAPTURED EQU     $171E           ; 1 byte: flag
DIAG_X_AFTER_M8 EQU     $1720           ; 2 bytes: X after PULS in M8_LOOP
* ---- Decimal conversion scratch ----
DEC_BUF         EQU     $1730           ; 5 bytes: 4 digits + NUL
DEC_DTEMP       EQU     $1736           ; 2 bytes: divisor scratch
DEC_SCRPTR      EQU     $1738           ; 2 bytes: saved screen X

* ============================================================
* RUN_TESTS — walk vectors.bin, call FXMATH, compare results
* ============================================================
RUN_TESTS:
                CLRA
                CLRB
                STD     PASS_M8
                STD     FAIL_M8
                STD     PASS_M15
                STD     FAIL_M15

* Verify magic "FX"
                LDX     #VECS
                LDA     ,X
                CMPA    #$46            ; 'F'
                LBNE    MAGIC_FAIL
                LDA     1,X
                CMPA    #$58            ; 'X'
                LBNE    MAGIC_FAIL

* Read n_mul8q15 count and advance past 8-byte header
                LDD     4,X             ; D = n_mul8q15
                STD     LOOP_CNT
                LEAX    8,X             ; X -> first MUL8Q15 record

* Zero M8 X diagnostic
                CLR     DIAG_X_AFTER_M8
                CLR     DIAG_X_AFTER_M8+1

* -------- MUL8Q15 test loop --------
* Record layout (5 bytes): a_q8[1], b_q15[2], expected[2]
M8_LOOP:
                LDD     LOOP_CNT
                BEQ     M8_DONE
                LDB     ,X              ; B = a_q8 (signed 8-bit)
                LEAY    1,X             ; Y -> b_q15 in record
                PSHS    X               ; save record pointer
                JSR     FX_MUL_Q8Q15    ; D = Q15 result
                PULS    X               ; restore record pointer
                STX     DIAG_X_AFTER_M8 ; diagnostic: capture X post-PULS (every iter)
                CMPD    3,X             ; compare D with expected at offset 3
                BEQ     M8_PASS
                JSR     INC_FAIL_M8
                BRA     M8_NEXT
M8_PASS:
                JSR     INC_PASS_M8
M8_NEXT:
                LEAX    5,X             ; advance to next record
                LDD     LOOP_CNT
                SUBD    #1
                STD     LOOP_CNT
                BRA     M8_LOOP
M8_DONE:

* Read n_mul15q15 count from original header
                LDY     #VECS
                LDD     6,Y             ; D = n_mul15q15
                STD     LOOP_CNT
* X already points past all MUL8Q15 records

* Zero diagnostic flags before M15 loop
                CLR     DIAG_M15_DONE
                CLR     DIAG_X_CAPTURED

* -------- MUL15Q15 test loop --------
* Record layout (6 bytes): a_q15[2], b_q15[2], expected[2]
M15_LOOP:
* ---- DIAGNOSTIC: capture X on first iteration ----
                LDA     DIAG_X_CAPTURED
                BNE     M15_X_SKIP
                STX     DIAG_X_AT_M15
                LDA     #1
                STA     DIAG_X_CAPTURED
M15_X_SKIP:
* ---- end X capture ----

                LDD     LOOP_CNT
                BEQ     M15_DONE

* ---- DIAGNOSTIC: capture first record inputs ----
                LDA     DIAG_M15_DONE
                BNE     M15_SKIP_CAP
                LDD     ,X              ; a_q15
                STD     DIAG_M15
                LDD     2,X             ; b_q15
                STD     DIAG_M15+2
                LDD     4,X             ; expected
                STD     DIAG_M15+4
M15_SKIP_CAP:
* ---- end input capture ----

                LDD     ,X              ; D = a_q15
                LEAY    2,X             ; Y -> b_q15 in record
                PSHS    X               ; save record pointer
                JSR     FX_MUL_Q15Q15   ; D = Q15 result

* ---- DIAGNOSTIC: capture first record actual result ----
                STD     DIAG_TEMP       ; save result (always, cheap)
                LDA     DIAG_M15_DONE
                BNE     M15_SKIP_ACT
                LDD     DIAG_TEMP       ; load result back
                STD     DIAG_M15+6      ; store actual
                LDA     #1
                STA     DIAG_M15_DONE   ; mark captured
M15_SKIP_ACT:
                LDD     DIAG_TEMP       ; restore D for comparison
* ---- end result capture ----

                PULS    X               ; restore record pointer
                CMPD    4,X             ; compare D with expected at offset 4
                BEQ     M15_PASS
                JSR     INC_FAIL_M15
                BRA     M15_NEXT
M15_PASS:
                JSR     INC_PASS_M15
M15_NEXT:
                LEAX    6,X             ; advance to next record
                LDD     LOOP_CNT
                SUBD    #1
                STD     LOOP_CNT
                BRA     M15_LOOP
M15_DONE:
                RTS

* -------- Magic check failure --------
MAGIC_FAIL:
                LDX     #SCREEN
                LDU     #BADHDR_MSG
MF_LOOP:
                LDA     ,U+
                BEQ     MF_DONE
                STA     ,X+
                BRA     MF_LOOP
MF_DONE:
                LBRA    HALT

* ============================================================
* Helpers — per-routine counter increment
* ============================================================
INC_PASS_M8:
                LDD     PASS_M8
                ADDD    #1
                STD     PASS_M8
                RTS

INC_FAIL_M8:
                LDD     FAIL_M8
                ADDD    #1
                STD     FAIL_M8
                RTS

INC_PASS_M15:
                LDD     PASS_M15
                ADDD    #1
                STD     PASS_M15
                RTS

INC_FAIL_M15:
                LDD     FAIL_M15
                ADDD    #1
                STD     FAIL_M15
                RTS

* ============================================================
* CLEAR_SCREEN — fill 512 bytes at SCREEN with $20 (space)
* Uses TFM for speed: seed first byte, propagate via block copy.
* ============================================================
CLEAR_SCREEN:
                LDA     #$20            ; ASCII space
                STA     SCREEN          ; seed first byte
                LDX     #SCREEN
                LDU     #SCREEN+1
                LDW     #511
                TFM     X+,U+           ; propagate $20 through buffer
                RTS

* ============================================================
* DISPLAY_RESULTS — write split summary to screen
* Row 0: "M8:  P=nnnn F=nnnn"
* Row 1: "M15: P=nnnn F=nnnn"
* Row 2: "DONE"
* ============================================================
DISPLAY_RESULTS:
* Row 0 — MUL8Q15
                LDX     #SCREEN
                LDU     #M8_LABEL
                JSR     COPY_STRING     ; "M8:  P="
                LDD     PASS_M8
                JSR     WRITE_DECIMAL_4
                LDU     #MID_LABEL
                JSR     COPY_STRING     ; " F="
                LDD     FAIL_M8
                JSR     WRITE_DECIMAL_4
* Row 1 — MUL15Q15
                LDX     #SCREEN+32
                LDU     #M15_LABEL
                JSR     COPY_STRING     ; "M15: P="
                LDD     PASS_M15
                JSR     WRITE_DECIMAL_4
                LDU     #MID_LABEL
                JSR     COPY_STRING     ; " F="
                LDD     FAIL_M15
                JSR     WRITE_DECIMAL_4
* Row 2 — DONE
                LDX     #SCREEN+64
                LDU     #DONE_LABEL
                JSR     COPY_STRING
                RTS

* ============================================================
* COPY_STRING — copy NUL-terminated string from U to screen X
* Entry: U -> source string, X -> screen destination
* Exit:  both U and X advanced past the copied bytes
* ============================================================
COPY_STRING:
                LDA     ,U+
                BEQ     CS_DONE
                STA     ,X+
                BRA     COPY_STRING
CS_DONE:
                RTS

* ============================================================
* WRITE_DECIMAL_4 — convert 16-bit value to 4 ASCII digits
* Entry: D = value (0-9999), X = screen pointer
* Exit:  X advanced by 4
* Uses scratch at DEC_BUF, DEC_DTEMP, DEC_SCRPTR.
* Method: repeated subtraction with divisor table (1000,100,10).
* ============================================================
WRITE_DECIMAL_4:
                STX     DEC_SCRPTR      ; save screen pointer
                LDU     #DEC_BUF        ; U -> digit output buffer
                LDX     #DIV_TABLE      ; X -> divisor table
                JSR     WD4_DIGIT       ; thousands
                JSR     WD4_DIGIT       ; hundreds
                JSR     WD4_DIGIT       ; tens
                ADDB    #$30            ; ones: remainder is last digit
                STB     ,U
* Copy 4 digits from buffer to screen
                LDX     DEC_SCRPTR
                LDD     DEC_BUF
                STD     ,X++
                LDD     DEC_BUF+2
                STD     ,X++
                RTS

* WD4_DIGIT — extract one decimal digit via repeated subtraction
* Entry: D = current value, X -> divisor table (word), U -> output
* Exit:  digit ASCII stored at ,U++, D = remainder, X += 2
WD4_DIGIT:
                LDY     ,X++            ; Y = divisor, advance table ptr
                STY     DEC_DTEMP       ; store divisor for SUBD
                LDY     #$002F          ; digit counter = '0' - 1
WD4_LOOP:
                LEAY    1,Y             ; increment digit counter
                SUBD    DEC_DTEMP       ; D -= divisor
                BCC     WD4_LOOP        ; no borrow -> divisor still fits
                ADDD    DEC_DTEMP       ; restore: undo last subtraction
                PSHS    D               ; save remainder
                TFR     Y,D             ; D = counter (low byte = ASCII digit)
                STB     ,U+             ; store ASCII digit to buffer
                PULS    D               ; restore remainder
                RTS

DIV_TABLE:
                FDB     1000
                FDB     100
                FDB     10

* ============================================================
* String constants
* ============================================================
M8_LABEL:       FCC     "M8:  P="
                FCB     0
M15_LABEL:      FCC     "M15: P="
                FCB     0
MID_LABEL:      FCC     " F="
                FCB     0
DONE_LABEL:     FCC     "DONE"
                FCB     0
BADHDR_MSG:     FCC     "BAD VECTORS.BIN HEADER"
                FCB     0

* ============================================================
* FXMATH code (included inline — flat binary composition)
* ============================================================
                INCLUDE src/fxmath.asm

* ============================================================
* Test vectors — loaded separately by Lua at $4800
* ============================================================
* vectors.bin is NOT included inline because the code region
* crosses the hardware-mapped screen buffer ($0400-$05FF).
* The Lua test runner loads vectors.bin directly at $4800
* (FREE_BASE from memory map) before setting PC.
VECS            EQU     $4800

                END     START
