* ============================================================
* t_proj.asm — PROJ test harness
* ============================================================
* 5 tests for PROJ output projection (per-position VTMUL wrapper).
* Per-test reporting via result bitmap at $1704 (1 byte, 5 bits used).
* Dependencies: equates.inc, macros.inc, fxmath.asm, vecop.asm,
*               matop.asm (VTMUL), layer.asm (PROJ)
* Vectors: tables/proj_vectors.asm (generated by gen_proj_vectors.py)
* ============================================================

                INCLUDE include/equates.inc
                INCLUDE include/macros.inc
                INCLUDE include/fxmath.inc

                ORG     $0600

* -------- Entry point --------
START:
                ORCC    #$50
                LDMD    #1
                LDS     #STACK_TOP
                JSR     CLEAR_SCREEN
                JSR     RUN_TESTS
                JSR     DISPLAY_RESULTS
HALT:           BRA     HALT

* -------- Scratch RAM --------
PASS_CNT        EQU     $1700
FAIL_CNT        EQU     $1702
RESULT_BITS     EQU     $1704
LAST_FAIL_ID    EQU     $1705
CUR_TEST_ID     EQU     $1706
DEC_BUF         EQU     $1730
DEC_DTEMP       EQU     $1736
DEC_SCRPTR      EQU     $1738

* -------- Test data buffers --------
* Y_BUF:    SEQ*DIM*2 bytes max = 8*16*2 = 256 bytes  ($1760-$185F)
* WOUT_BUF: DIM*VOC*2 bytes max = 16*10*2 = 320 bytes ($1860-$19BF)
* OUT_BUF:  SEQ*VOC*2 bytes max = 8*10*2 = 160 bytes  ($19C0-$1A5F)
Y_BUF           EQU     $1760
WOUT_BUF        EQU     $1860
OUT_BUF         EQU     $19C0

* ============================================================
* RUN_TESTS
* ============================================================
RUN_TESTS:
                CLRA
                CLRB
                STD     PASS_CNT
                STD     FAIL_CNT
                CLR     RESULT_BITS
                LDA     #$FF
                STA     LAST_FAIL_ID

                JSR     TEST_0
                JSR     TEST_1
                JSR     TEST_2
                JSR     TEST_3
                JSR     TEST_4
                RTS

* ============================================================
* Framework helpers
* ============================================================
LOAD_BUF:
                CMPW    #0
                BEQ     LB_EXIT
LB_LOOP:
                LDD     ,X++
                STD     ,Y++
                DECW
                BNE     LB_LOOP
LB_EXIT:
                RTS

RECORD_PASS:
                LDD     PASS_CNT
                ADDD    #1
                STD     PASS_CNT
                LDA     CUR_TEST_ID
                LDB     #1
RP_SHIFT:
                TSTA
                BEQ     RP_DONE
                LSLB
                DECA
                BRA     RP_SHIFT
RP_DONE:
                ORB     RESULT_BITS
                STB     RESULT_BITS
                RTS

RECORD_FAIL:
                LDD     FAIL_CNT
                ADDD    #1
                STD     FAIL_CNT
                LDA     CUR_TEST_ID
                STA     LAST_FAIL_ID
                RTS

* ============================================================
* Test 0: PROJ_SINGLE  (SEQ=1 DIM=4 VOC=3)
* ============================================================
TEST_0:
                CLR     CUR_TEST_ID
                LDX     #Y_0
                LDY     #Y_BUF
                LDW     Y_CNT_0
                JSR     LOAD_BUF
                LDX     #WOUT_0
                LDY     #WOUT_BUF
                LDW     WOUT_CNT_0
                JSR     LOAD_BUF
                LDD     #Y_BUF
                STD     PR_Y
                LDD     #WOUT_BUF
                STD     PR_WOUT
                LDD     #OUT_BUF
                STD     PR_LOG
                LDD     SEQ_0
                STD     PR_SEQ
                LDD     DIM_0
                STD     PR_DIM
                LDD     VOC_0
                STD     PR_VOC
                JSR     PROJ
                LDX     #OUT_BUF
                LDY     #EXPECT_0
                LDW     CNT_0
T0_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T0_FAIL
                DECW
                BNE     T0_CHK
                JSR     RECORD_PASS
                RTS
T0_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 1: PROJ_SEQ4  (SEQ=4 DIM=8 VOC=5)
* ============================================================
TEST_1:
                LDA     #1
                STA     CUR_TEST_ID
                LDX     #Y_1
                LDY     #Y_BUF
                LDW     Y_CNT_1
                JSR     LOAD_BUF
                LDX     #WOUT_1
                LDY     #WOUT_BUF
                LDW     WOUT_CNT_1
                JSR     LOAD_BUF
                LDD     #Y_BUF
                STD     PR_Y
                LDD     #WOUT_BUF
                STD     PR_WOUT
                LDD     #OUT_BUF
                STD     PR_LOG
                LDD     SEQ_1
                STD     PR_SEQ
                LDD     DIM_1
                STD     PR_DIM
                LDD     VOC_1
                STD     PR_VOC
                JSR     PROJ
                LDX     #OUT_BUF
                LDY     #EXPECT_1
                LDW     CNT_1
T1_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T1_FAIL
                DECW
                BNE     T1_CHK
                JSR     RECORD_PASS
                RTS
T1_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 2: PROJ_FULL  (SEQ=8 DIM=16 VOC=10 — architecture max)
* ============================================================
TEST_2:
                LDA     #2
                STA     CUR_TEST_ID
                LDX     #Y_2
                LDY     #Y_BUF
                LDW     Y_CNT_2
                JSR     LOAD_BUF
                LDX     #WOUT_2
                LDY     #WOUT_BUF
                LDW     WOUT_CNT_2
                JSR     LOAD_BUF
                LDD     #Y_BUF
                STD     PR_Y
                LDD     #WOUT_BUF
                STD     PR_WOUT
                LDD     #OUT_BUF
                STD     PR_LOG
                LDD     SEQ_2
                STD     PR_SEQ
                LDD     DIM_2
                STD     PR_DIM
                LDD     VOC_2
                STD     PR_VOC
                JSR     PROJ
                LDX     #OUT_BUF
                LDY     #EXPECT_2
                LDW     CNT_2
T2_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T2_FAIL
                DECW
                BNE     T2_CHK
                JSR     RECORD_PASS
                RTS
T2_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 3: PROJ_SAT_POS  (saturation divergence — positive)
* ============================================================
TEST_3:
                LDA     #3
                STA     CUR_TEST_ID
                LDX     #Y_3
                LDY     #Y_BUF
                LDW     Y_CNT_3
                JSR     LOAD_BUF
                LDX     #WOUT_3
                LDY     #WOUT_BUF
                LDW     WOUT_CNT_3
                JSR     LOAD_BUF
                LDD     #Y_BUF
                STD     PR_Y
                LDD     #WOUT_BUF
                STD     PR_WOUT
                LDD     #OUT_BUF
                STD     PR_LOG
                LDD     SEQ_3
                STD     PR_SEQ
                LDD     DIM_3
                STD     PR_DIM
                LDD     VOC_3
                STD     PR_VOC
                JSR     PROJ
                LDX     #OUT_BUF
                LDY     #EXPECT_3
                LDW     CNT_3
T3_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T3_FAIL
                DECW
                BNE     T3_CHK
                JSR     RECORD_PASS
                RTS
T3_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 4: PROJ_SAT_NEG  (saturation divergence — negative)
* ============================================================
TEST_4:
                LDA     #4
                STA     CUR_TEST_ID
                LDX     #Y_4
                LDY     #Y_BUF
                LDW     Y_CNT_4
                JSR     LOAD_BUF
                LDX     #WOUT_4
                LDY     #WOUT_BUF
                LDW     WOUT_CNT_4
                JSR     LOAD_BUF
                LDD     #Y_BUF
                STD     PR_Y
                LDD     #WOUT_BUF
                STD     PR_WOUT
                LDD     #OUT_BUF
                STD     PR_LOG
                LDD     SEQ_4
                STD     PR_SEQ
                LDD     DIM_4
                STD     PR_DIM
                LDD     VOC_4
                STD     PR_VOC
                JSR     PROJ
                LDX     #OUT_BUF
                LDY     #EXPECT_4
                LDW     CNT_4
T4_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T4_FAIL
                DECW
                BNE     T4_CHK
                JSR     RECORD_PASS
                RTS
T4_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Display helpers
* ============================================================
CLEAR_SCREEN:
                LDA     #$20
                STA     SCREEN
                LDX     #SCREEN
                LDU     #SCREEN+1
                LDW     #511
                TFM     X+,U+
                RTS

DISPLAY_RESULTS:
                LDX     #SCREEN
                LDU     #LBL_PASS
                JSR     COPY_STRING
                LDD     PASS_CNT
                JSR     WRITE_DECIMAL_4
                LDU     #LBL_MID
                JSR     COPY_STRING
                LDD     FAIL_CNT
                JSR     WRITE_DECIMAL_4
                LDX     #SCREEN+32
                LDU     #LBL_BITS
                JSR     COPY_STRING
                CLRA
                LDB     RESULT_BITS
                JSR     WRITE_HEX_4
                LDU     #LBL_LF
                JSR     COPY_STRING
                CLRA
                LDB     LAST_FAIL_ID
                JSR     WRITE_HEX_4
                LDX     #SCREEN+64
                LDU     #LBL_DONE
                JSR     COPY_STRING
                RTS

COPY_STRING:
                LDA     ,U+
                BEQ     CS_DONE
                STA     ,X+
                BRA     COPY_STRING
CS_DONE:        RTS

WRITE_DECIMAL_4:
                STX     DEC_SCRPTR
                LDU     #DEC_BUF
                LDX     #DIV_TABLE
                JSR     WD4_DIGIT
                JSR     WD4_DIGIT
                JSR     WD4_DIGIT
                ADDB    #$30
                STB     ,U
                LDX     DEC_SCRPTR
                LDD     DEC_BUF
                STD     ,X++
                LDD     DEC_BUF+2
                STD     ,X++
                RTS

WD4_DIGIT:
                LDY     ,X++
                STY     DEC_DTEMP
                LDY     #$002F
WD4_LOOP:
                LEAY    1,Y
                SUBD    DEC_DTEMP
                BCC     WD4_LOOP
                ADDD    DEC_DTEMP
                PSHS    D
                TFR     Y,D
                STB     ,U+
                PULS    D
                RTS

WRITE_HEX_4:
                PSHS    D
                LDA     ,S
                JSR     WHEX_BYTE
                LDA     1,S
                JSR     WHEX_BYTE
                LEAS    2,S
                RTS

WHEX_BYTE:
                PSHS    A
                LSRA
                LSRA
                LSRA
                LSRA
                JSR     WHEX_NIB
                PULS    A
                ANDA    #$0F
                JSR     WHEX_NIB
                RTS

WHEX_NIB:
                CMPA    #10
                BLT     WHEX_D
                ADDA    #'A-10
                BRA     WHEX_OUT
WHEX_D:
                ADDA    #'0
WHEX_OUT:
                STA     ,X+
                RTS

DIV_TABLE:      FDB     1000
                FDB     100
                FDB     10

LBL_PASS:       FCC     "PRJ: P="
                FCB     0
LBL_MID:        FCC     " F="
                FCB     0
LBL_BITS:       FCC     "B="
                FCB     0
LBL_LF:         FCC     " LF="
                FCB     0
LBL_DONE:       FCC     "DONE"
                FCB     0

                INCLUDE src/fxmath.asm
                INCLUDE src/vecop.asm
                INCLUDE src/matop.asm
                INCLUDE src/layer.asm

                INCLUDE tables/proj_vectors.asm

                END     START
