* ============================================================
* t_vsadd.asm — VSADD test harness
* ============================================================
* 10 tests for VSADD two-stage clamp semantics.
* Per-test reporting via result bitmap at $1704 (2 bytes, 10 bits used).
* Dependencies: equates.inc, macros.inc, fxmath.asm, vecop.asm
* Vectors: tables/vsadd_vectors.asm (generated by gen_vsadd_vectors.py)
* ============================================================

                INCLUDE include/equates.inc
                INCLUDE include/macros.inc
                INCLUDE include/fxmath.inc

                ORG     $0600

* -------- Entry point --------
START:
                ORCC    #$50
                LDMD    #1
                LDS     #STACK_TOP
                JSR     CLEAR_SCREEN
                JSR     RUN_TESTS
                JSR     DISPLAY_RESULTS
HALT:           BRA     HALT

* -------- Scratch RAM --------
PASS_CNT        EQU     $1700           ; 2B total pass count
FAIL_CNT        EQU     $1702           ; 2B total fail count
RESULT_BITS     EQU     $1704           ; 2B bitmap (bits 0-9 used)
LAST_FAIL_ID    EQU     $1706           ; 1B last-failed test ID ($FF if none)
CUR_TEST_ID     EQU     $1707           ; 1B currently-executing test ID
DEC_BUF         EQU     $1730           ; 5B decimal scratch
DEC_DTEMP       EQU     $1736           ; 2B
DEC_SCRPTR      EQU     $1738           ; 2B

* -------- Test data buffers (sized for Test 9: 16 words) --------
DST_BUF         EQU     $1760           ; 40B destination buffer
SRC_BUF         EQU     $1790           ; 40B source buffer

* ============================================================
* RUN_TESTS — run all 10 tests, record per-test pass/fail
* ============================================================
RUN_TESTS:
                CLRA
                CLRB
                STD     PASS_CNT
                STD     FAIL_CNT
                STD     RESULT_BITS
                LDA     #$FF
                STA     LAST_FAIL_ID

                JSR     TEST_0          ; VSADD_ZERO_SCL
                JSR     TEST_1          ; VSADD_UNIT_SCL
                JSR     TEST_2          ; VSADD_POS_NOSAT
                JSR     TEST_3          ; VSADD_NEG_NOSAT
                JSR     TEST_4          ; VSADD_PRODUCT_SAT (divergence)
                JSR     TEST_5          ; VSADD_SUM_SAT
                JSR     TEST_6          ; VSADD_BOTH_SAT
                JSR     TEST_7          ; VSADD_LEN0
                JSR     TEST_8          ; VSADD_LEN1
                JSR     TEST_9          ; VSADD_LEN16_MIXED
                RTS

* ============================================================
* Framework helpers
* ============================================================

* FILL_BUF — fill memory with a 16-bit value
* Entry: X -> buffer, D = value, W = word count
* Zero-guard: W=0 is a no-op.
FILL_BUF:
                CMPW    #0
                BEQ     FB_EXIT
FB_LOOP:
                STD     ,X++
                DECW
                BNE     FB_LOOP
FB_EXIT:
                RTS

* LOAD_BUF — copy W words from X to Y
* Entry: X -> source, Y -> dest, W = word count
* Zero-guard: W=0 is a no-op.
LOAD_BUF:
                CMPW    #0
                BEQ     LB_EXIT
LB_LOOP:
                LDD     ,X++
                STD     ,Y++
                DECW
                BNE     LB_LOOP
LB_EXIT:
                RTS

* RECORD_PASS — increment PASS_CNT, set bit for CUR_TEST_ID
* Counter preserved on stack across LDD (which clobbers A).
RECORD_PASS:
                LDD     PASS_CNT
                ADDD    #1
                STD     PASS_CNT
                LDA     CUR_TEST_ID
                PSHS    A               ; save counter across LDD
                LDD     #1              ; D = starting bitmask $0001
RP_SHIFT:
                TST     ,S              ; test counter on stack
                BEQ     RP_DONE
                LSLD                    ; shift bitmask left
                DEC     ,S              ; decrement counter
                BRA     RP_SHIFT
RP_DONE:
                LEAS    1,S             ; drop counter
                ORD     RESULT_BITS
                STD     RESULT_BITS
                RTS

* RECORD_FAIL — increment FAIL_CNT, store CUR_TEST_ID to LAST_FAIL_ID
RECORD_FAIL:
                LDD     FAIL_CNT
                ADDD    #1
                STD     FAIL_CNT
                LDA     CUR_TEST_ID
                STA     LAST_FAIL_ID
                RTS

* ============================================================
* Test 0: VSADD_ZERO_SCL — scalar=0, dst unchanged
* Length 4, no bounds check needed (verifying all 4 elements).
* ============================================================
TEST_0:
                CLR     CUR_TEST_ID
* Load DST_BUF from DST_0_INIT (4 words)
                LDX     #DST_0_INIT
                LDY     #DST_BUF
                LDW     #4
                JSR     LOAD_BUF
* Load SRC_BUF from SRC_0 (4 words)
                LDX     #SRC_0
                LDY     #SRC_BUF
                LDW     #4
                JSR     LOAD_BUF
* Set VSADD params
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_0
                STD     VS_SCL
                LDD     LEN_0
                STD     VS_LEN
                JSR     VSADD
* Verify DST_BUF matches EXPECT_0 for LEN_0 (4) words
                LDX     #DST_BUF
                LDY     #EXPECT_0
                LDW     #4
T0_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T0_FAIL
                DECW
                BNE     T0_CHK
                JSR     RECORD_PASS
                RTS
T0_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 1: VSADD_UNIT_SCL — scalar=256, dst += src
* ============================================================
TEST_1:
                LDA     #1
                STA     CUR_TEST_ID
                LDX     #DST_1_INIT
                LDY     #DST_BUF
                LDW     #4
                JSR     LOAD_BUF
                LDX     #SRC_1
                LDY     #SRC_BUF
                LDW     #4
                JSR     LOAD_BUF
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_1
                STD     VS_SCL
                LDD     LEN_1
                STD     VS_LEN
                JSR     VSADD
                LDX     #DST_BUF
                LDY     #EXPECT_1
                LDW     #4
T1_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T1_FAIL
                DECW
                BNE     T1_CHK
                JSR     RECORD_PASS
                RTS
T1_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 2: VSADD_POS_NOSAT — positive scalar, no saturation
* ============================================================
TEST_2:
                LDA     #2
                STA     CUR_TEST_ID
                LDX     #DST_2_INIT
                LDY     #DST_BUF
                LDW     #4
                JSR     LOAD_BUF
                LDX     #SRC_2
                LDY     #SRC_BUF
                LDW     #4
                JSR     LOAD_BUF
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_2
                STD     VS_SCL
                LDD     LEN_2
                STD     VS_LEN
                JSR     VSADD
                LDX     #DST_BUF
                LDY     #EXPECT_2
                LDW     #4
T2_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T2_FAIL
                DECW
                BNE     T2_CHK
                JSR     RECORD_PASS
                RTS
T2_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 3: VSADD_NEG_NOSAT — negative scalar, sign-preserving shift
* ============================================================
TEST_3:
                LDA     #3
                STA     CUR_TEST_ID
                LDX     #DST_3_INIT
                LDY     #DST_BUF
                LDW     #4
                JSR     LOAD_BUF
                LDX     #SRC_3
                LDY     #SRC_BUF
                LDW     #4
                JSR     LOAD_BUF
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_3
                STD     VS_SCL
                LDD     LEN_3
                STD     VS_LEN
                JSR     VSADD
                LDX     #DST_BUF
                LDY     #EXPECT_3
                LDW     #4
T3_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T3_FAIL
                DECW
                BNE     T3_CHK
                JSR     RECORD_PASS
                RTS
T3_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 4: VSADD_PRODUCT_SAT — DIVERGENCE TEST
* Single-clamp would give 32767; two-stage gives 12767.
* ============================================================
TEST_4:
                LDA     #4
                STA     CUR_TEST_ID
                LDX     #DST_4_INIT
                LDY     #DST_BUF
                LDW     #1
                JSR     LOAD_BUF
                LDX     #SRC_4
                LDY     #SRC_BUF
                LDW     #1
                JSR     LOAD_BUF
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_4
                STD     VS_SCL
                LDD     LEN_4
                STD     VS_LEN
                JSR     VSADD
                LDX     #DST_BUF
                LDY     #EXPECT_4
                LDW     #1
T4_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T4_FAIL
                DECW
                BNE     T4_CHK
                JSR     RECORD_PASS
                RTS
T4_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 5: VSADD_SUM_SAT — product in range, sum saturates
* ============================================================
TEST_5:
                LDA     #5
                STA     CUR_TEST_ID
                LDX     #DST_5_INIT
                LDY     #DST_BUF
                LDW     #1
                JSR     LOAD_BUF
                LDX     #SRC_5
                LDY     #SRC_BUF
                LDW     #1
                JSR     LOAD_BUF
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_5
                STD     VS_SCL
                LDD     LEN_5
                STD     VS_LEN
                JSR     VSADD
                LDX     #DST_BUF
                LDY     #EXPECT_5
                LDW     #1
T5_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T5_FAIL
                DECW
                BNE     T5_CHK
                JSR     RECORD_PASS
                RTS
T5_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 6: VSADD_BOTH_SAT — product saturates, sum also would
* ============================================================
TEST_6:
                LDA     #6
                STA     CUR_TEST_ID
                LDX     #DST_6_INIT
                LDY     #DST_BUF
                LDW     #1
                JSR     LOAD_BUF
                LDX     #SRC_6
                LDY     #SRC_BUF
                LDW     #1
                JSR     LOAD_BUF
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_6
                STD     VS_SCL
                LDD     LEN_6
                STD     VS_LEN
                JSR     VSADD
                LDX     #DST_BUF
                LDY     #EXPECT_6
                LDW     #1
T6_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T6_FAIL
                DECW
                BNE     T6_CHK
                JSR     RECORD_PASS
                RTS
T6_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 7: VSADD_LEN0 — zero-length no-op (bounds check: all 4 words)
* Load full DST_7_INIT (4 words) into DST_BUF, call VSADD with len=0,
* verify all 4 DST_BUF words still match DST_7_INIT unchanged.
* ============================================================
TEST_7:
                LDA     #7
                STA     CUR_TEST_ID
* Load full 4-word init pattern for bounds check
                LDX     #DST_7_INIT
                LDY     #DST_BUF
                LDW     #4
                JSR     LOAD_BUF
                LDX     #SRC_7
                LDY     #SRC_BUF
                LDW     #4
                JSR     LOAD_BUF
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_7
                STD     VS_SCL
                LDD     LEN_7           ; = 0
                STD     VS_LEN
                JSR     VSADD
* Verify DST_BUF[0..3] unchanged — EXPECT_7 equals DST_7_INIT
                LDX     #DST_BUF
                LDY     #EXPECT_7
                LDW     #4
T7_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T7_FAIL
                DECW
                BNE     T7_CHK
                JSR     RECORD_PASS
                RTS
T7_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 8: VSADD_LEN1 — single-element update with bounds check
* Load full 2-word DST_8_INIT ($100, $9999), call VSADD with len=1,
* verify DST_BUF[0] = EXPECT_8[0] and DST_BUF[1] = DST_8_INIT[1] ($9999).
* ============================================================
TEST_8:
                LDA     #8
                STA     CUR_TEST_ID
* Load full 2-word init pattern
                LDX     #DST_8_INIT
                LDY     #DST_BUF
                LDW     #2
                JSR     LOAD_BUF
                LDX     #SRC_8
                LDY     #SRC_BUF
                LDW     #2
                JSR     LOAD_BUF
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_8
                STD     VS_SCL
                LDD     LEN_8           ; = 1
                STD     VS_LEN
                JSR     VSADD
* Verify DST_BUF[0] = EXPECT_8[0]
                LDX     #DST_BUF
                LDD     ,X
                CMPD    EXPECT_8
                LBNE    T8_FAIL
* Verify DST_BUF[1] = DST_8_INIT[1] (bounds: sentinel $9999 untouched)
                LDD     2,X
                CMPD    DST_8_INIT+2
                LBNE    T8_FAIL
                JSR     RECORD_PASS
                RTS
T8_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Test 9: VSADD_LEN16_MIXED — 16 elements, mixed signs and saturation
* ============================================================
TEST_9:
                LDA     #9
                STA     CUR_TEST_ID
                LDX     #DST_9_INIT
                LDY     #DST_BUF
                LDW     #16
                JSR     LOAD_BUF
                LDX     #SRC_9
                LDY     #SRC_BUF
                LDW     #16
                JSR     LOAD_BUF
                LDD     #SRC_BUF
                STD     VS_SRC
                LDD     #DST_BUF
                STD     VS_DST
                LDD     SCL_9
                STD     VS_SCL
                LDD     LEN_9
                STD     VS_LEN
                JSR     VSADD
                LDX     #DST_BUF
                LDY     #EXPECT_9
                LDW     #16
T9_CHK:
                LDD     ,X++
                CMPD    ,Y++
                LBNE    T9_FAIL
                DECW
                BNE     T9_CHK
                JSR     RECORD_PASS
                RTS
T9_FAIL:
                JSR     RECORD_FAIL
                RTS

* ============================================================
* Display / screen / decimal helpers (duplicated from t_vcpycl.asm)
* ============================================================
CLEAR_SCREEN:
                LDA     #$20
                STA     SCREEN
                LDX     #SCREEN
                LDU     #SCREEN+1
                LDW     #511
                TFM     X+,U+
                RTS

DISPLAY_RESULTS:
                LDX     #SCREEN
                LDU     #LBL_PASS
                JSR     COPY_STRING
                LDD     PASS_CNT
                JSR     WRITE_DECIMAL_4
                LDU     #LBL_MID
                JSR     COPY_STRING
                LDD     FAIL_CNT
                JSR     WRITE_DECIMAL_4
* Row 1: bitmap (hex) and last-fail ID
                LDX     #SCREEN+32
                LDU     #LBL_BITS
                JSR     COPY_STRING
                LDD     RESULT_BITS
                JSR     WRITE_HEX_4
                LDU     #LBL_LF
                JSR     COPY_STRING
                CLRA
                LDB     LAST_FAIL_ID
                JSR     WRITE_HEX_4
                LDX     #SCREEN+64
                LDU     #LBL_DONE
                JSR     COPY_STRING
                RTS

COPY_STRING:
                LDA     ,U+
                BEQ     CS_DONE
                STA     ,X+
                BRA     COPY_STRING
CS_DONE:        RTS

WRITE_DECIMAL_4:
                STX     DEC_SCRPTR
                LDU     #DEC_BUF
                LDX     #DIV_TABLE
                JSR     WD4_DIGIT
                JSR     WD4_DIGIT
                JSR     WD4_DIGIT
                ADDB    #$30
                STB     ,U
                LDX     DEC_SCRPTR
                LDD     DEC_BUF
                STD     ,X++
                LDD     DEC_BUF+2
                STD     ,X++
                RTS

WD4_DIGIT:
                LDY     ,X++
                STY     DEC_DTEMP
                LDY     #$002F
WD4_LOOP:
                LEAY    1,Y
                SUBD    DEC_DTEMP
                BCC     WD4_LOOP
                ADDD    DEC_DTEMP
                PSHS    D
                TFR     Y,D
                STB     ,U+
                PULS    D
                RTS

* WRITE_HEX_4 — write D as 4 hex digits to ,X++ (uppercase)
WRITE_HEX_4:
                PSHS    D
                LDA     ,S              ; high byte of D
                JSR     WHEX_BYTE
                LDA     1,S             ; low byte of D
                JSR     WHEX_BYTE
                LEAS    2,S
                RTS

WHEX_BYTE:
                PSHS    A
                LSRA
                LSRA
                LSRA
                LSRA
                JSR     WHEX_NIB
                PULS    A
                ANDA    #$0F
                JSR     WHEX_NIB
                RTS

WHEX_NIB:
                CMPA    #10
                BLT     WHEX_D
                ADDA    #'A-10
                BRA     WHEX_OUT
WHEX_D:
                ADDA    #'0
WHEX_OUT:
                STA     ,X+
                RTS

DIV_TABLE:      FDB     1000
                FDB     100
                FDB     10

LBL_PASS:       FCC     "VSA: P="
                FCB     0
LBL_MID:        FCC     " F="
                FCB     0
LBL_BITS:       FCC     "B="
                FCB     0
LBL_LF:         FCC     " LF="
                FCB     0
LBL_DONE:       FCC     "DONE"
                FCB     0

* ============================================================
* Include VECOP code (provides VSADD, VCPY, VCLR, VMAX, etc.)
* ============================================================
                INCLUDE src/fxmath.asm
                INCLUDE src/vecop.asm

* ============================================================
* Test vectors (generated)
* ============================================================
                INCLUDE tables/vsadd_vectors.asm

                END     START
