* ============================================================
* bkwrd23_vectors.asm — BKWRD Steps 2-3 test vectors
* Generated by gen_bkwrd23_vectors.py — do not hand-edit.
* Workspace layout per test: [Q zeros][K zeros][V data][A data]
* so BK_WRK = WORK_N puts V at BK_WRK+2*SEQ*DIM*2, A at +3*.
* ============================================================

* Test 0: BK23_T0_S2ONLY  SEQ=2 DIM=2 SHF=0  mode=step2_only
SEQ_0         FDB  2
DIM_0         FDB  2
SHF_0         FDB  0
WORK_0        FDB  0,0,0,0   ; Q region (unused)
WK_0K         FDB  0,0,0,0   ; K region (unused)
WK_0V         FDB  100,-50,-20,80   ; V region
WK_0A         FDB  64,192,128,128   ; A region
DY_0          FDB  1000,-500,2000,-1500
DA_CNT_0      FDB  4
DV_CNT_0      FDB  4
EXP_DA_0      FDB  488,-235,1074,-625
EXP_DV_0      FDB  1250,-875,1750,-1125

* Test 1: BK23_T1_CHAIN_TINY  SEQ=2 DIM=2 SHF=1  mode=chained
SEQ_1         FDB  2
DIM_1         FDB  2
SHF_1         FDB  1
WORK_1        FDB  0,0,0,0   ; Q region (unused)
WK_1K         FDB  0,0,0,0   ; K region (unused)
WK_1V         FDB  100,-50,-20,80   ; V region
WK_1A         FDB  64,192,128,128   ; A region
DY_1          FDB  1000,-500,2000,-1500
DA_CNT_1      FDB  4
DV_CNT_1      FDB  4
EXP_DV_1      FDB  1250,-875,1750,-1125
EXP_DSC_1     FDB  67,-68,212,-213

* Test 2: BK23_T2_CHAIN_MED  SEQ=4 DIM=8 SHF=3  mode=chained
SEQ_2         FDB  4
DIM_2         FDB  8
SHF_2         FDB  3
WORK_2        FDB  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0   ; Q region (unused)
WK_2K         FDB  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0   ; K region (unused)
WK_2V         FDB  -100,-89,-78,-67,-56,-45,-34,-23,-95,-84,-73,-62,-51,-40,-29,-18,-90,-79,-68,-57,-46,-35,-24,-13,-85,-74,-63,-52,-41,-30,-19,-8   ; V region
WK_2A         FDB  20,27,34,41,23,30,37,44,26,33,40,47,29,36,43,50   ; A region
DY_2          FDB  -2000,-1983,-1966,-1949,-1932,-1915,-1898,-1881,-1987,-1970,-1953,-1936,-1919,-1902,-1885,-1868,-1974,-1957,-1940,-1923,-1906,-1889,-1872,-1855,-1961,-1944,-1927,-1910,-1893,-1876,-1859,-1842
DA_CNT_2      FDB  16
DV_CNT_2      FDB  32
EXP_DV_2      FDB  -760,-752,-747,-740,-733,-726,-721,-713,-975,-968,-959,-950,-942,-933,-926,-918,-1193,-1182,-1173,-1161,-1151,-1142,-1132,-1120,-1410,-1397,-1385,-1374,-1360,-1348,-1336,-1325
EXP_DSC_2     FDB  21,25,26,26,23,25,26,24,24,25,25,22,24,25,23,20

* Test 3: BK23_T3_CLAMP  SEQ=2 DIM=4 SHF=0  mode=chained
SEQ_3         FDB  2
DIM_3         FDB  4
SHF_3         FDB  0
WORK_3        FDB  0,0,0,0,0,0,0,0   ; Q region (unused)
WK_3K         FDB  0,0,0,0,0,0,0,0   ; K region (unused)
WK_3V         FDB  32000,32000,0,0,0,0,-32000,-32000   ; V region
WK_3A         FDB  50,200,60,180   ; A region
DY_3          FDB  32000,32000,32000,32000,-32000,-32000,-32000,-32000
DA_CNT_3      FDB  4
DV_CNT_3      FDB  8
EXP_DV_3      FDB  -1250,-1250,-1250,-1250,2500,2500,2500,2500
EXP_DSC_3     FDB  6399,-10600,-7680,12240

