* ============================================================
* embed_vectors.asm — test vectors for EMBED harness
* Generated by gen_embed_vectors.py — do not hand-edit
* Wrapping arithmetic semantics (matches ATTN/11 assembly)
* ============================================================

* Test 0: EMBED_SINGLE_TOKEN
SEQ_0          FDB 1
DIM_0          FDB 4
CNT_0          FDB 4         ; seq * dim (output word count)
TKEMB_CNT_0    FDB 20         ; V * dim (tkemb word count)
TOK_0          FDB 3
* TKEMB_0 rows: V=5, dim=4, row-major
TKEMB_0        FDB 100,200,300,400,500,600,700,800,-100,-200,-300,-400,1000,2000,3000,4000,5,10,15,20
* PSEMB_0 rows: seq=1, dim=4
PSEMB_0        FDB 10,20,30,40
EXPECT_0       FDB 1010,2020,3030,4040

* Test 1: EMBED_SEQ2
SEQ_1          FDB 2
DIM_1          FDB 4
CNT_1          FDB 8         ; seq * dim (output word count)
TKEMB_CNT_1    FDB 20         ; V * dim (tkemb word count)
TOK_1          FDB 1,4
* TKEMB_1 rows: V=5, dim=4, row-major
TKEMB_1        FDB 100,100,100,100,200,200,200,200,300,300,300,300,400,400,400,400,500,500,500,500
* PSEMB_1 rows: seq=2, dim=4
PSEMB_1        FDB 1,2,3,4,10,20,30,40
EXPECT_1       FDB 201,202,203,204,510,520,530,540

* Test 2: EMBED_MAX_SEQ
SEQ_2          FDB 8
DIM_2          FDB 16
CNT_2          FDB 128         ; seq * dim (output word count)
TKEMB_CNT_2    FDB 160         ; V * dim (tkemb word count)
TOK_2          FDB 0,1,2,3,4,5,6,7
* TKEMB_2 rows: V=10, dim=16, row-major
TKEMB_2        FDB 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915
* PSEMB_2 rows: seq=8, dim=16
PSEMB_2        FDB 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100
EXPECT_2       FDB 0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,110,113,116,119,122,125,128,131,134,137,140,143,146,149,152,155,220,223,226,229,232,235,238,241,244,247,250,253,256,259,262,265,330,333,336,339,342,345,348,351,354,357,360,363,366,369,372,375,440,443,446,449,452,455,458,461,464,467,470,473,476,479,482,485,550,553,556,559,562,565,568,571,574,577,580,583,586,589,592,595,660,663,666,669,672,675,678,681,684,687,690,693,696,699,702,705,770,773,776,779,782,785,788,791,794,797,800,803,806,809,812,815

* Test 3: EMBED_TOKEN_ZERO
SEQ_3          FDB 2
DIM_3          FDB 4
CNT_3          FDB 8         ; seq * dim (output word count)
TKEMB_CNT_3    FDB 8         ; V * dim (tkemb word count)
TOK_3          FDB 0,0
* TKEMB_3 rows: V=2, dim=4, row-major
TKEMB_3        FDB 1111,2222,3333,4444,9999,9999,9999,9999
* PSEMB_3 rows: seq=2, dim=4
PSEMB_3        FDB 1,2,3,4,10,20,30,40
EXPECT_3       FDB 1112,2224,3336,4448,1121,2242,3363,4484

* Test 4: EMBED_TOKEN_MAX
SEQ_4          FDB 1
DIM_4          FDB 4
CNT_4          FDB 4         ; seq * dim (output word count)
TKEMB_CNT_4    FDB 40         ; V * dim (tkemb word count)
TOK_4          FDB 9
* TKEMB_4 rows: V=10, dim=4, row-major
TKEMB_4        FDB 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1000,-2000,-3000,-4000
* PSEMB_4 rows: seq=1, dim=4
PSEMB_4        FDB 5,10,15,20
EXPECT_4       FDB -995,-1990,-2985,-3980

* Test 5: EMBED_WRAP
*   DIVERGENCE from clamp16 semantics:
*   wrapping (ours/assembly):  -25536  ($9C40)
*   clamp16 (prototype):        32767   ($7FFF)
*
*   tkemb[0][0] = 30000
*   psemb[0][0] = 10000
*   raw sum     = 40000 (overflows Q15)
*   wrap: 40000 - 65536 = -25536
SEQ_5          FDB 1
DIM_5          FDB 1
CNT_5          FDB 1         ; seq * dim (output word count)
TKEMB_CNT_5    FDB 1         ; V * dim (tkemb word count)
TOK_5          FDB 0
* TKEMB_5 rows: V=1, dim=1, row-major
TKEMB_5        FDB 30000
* PSEMB_5 rows: seq=1, dim=1
PSEMB_5        FDB 10000
EXPECT_5       FDB -25536       ; wrapping; clamp16 would be 32767

