#!/usr/bin/env python3
"""
gen_exptbl.py — Generate EXPTBL lookup table for softmax.

Produces tables/exptbl.asm: 256 Q8 entries of exp(-i/32).
Matches ATTN/11 ACTFN.MAC and gen-lut.shf exactly.
"""

import math
from pathlib import Path

def q8_exp(i):
    """Q8 encode: round(exp(-i/32) * 256), clamped non-negative."""
    return max(0, int(math.exp(-i / 32.0) * 256.0 + 0.5))

def main():
    tbl = [q8_exp(i) for i in range(256)]

    # Cross-check against ACTFN.MAC key values
    checks = [(0, 256), (16, 155), (32, 94), (64, 35), (128, 5), (255, 0)]
    for idx, expected in checks:
        actual = tbl[idx]
        status = "OK" if actual == expected else "MISMATCH"
        print(f"  [{idx:3d}] = {actual:3d}  (expected {expected:3d})  {status}")
        assert actual == expected, f"EXPTBL[{idx}] mismatch: {actual} != {expected}"

    nonzero = sum(1 for v in tbl if v > 0)
    print(f"  Non-zero entries: {nonzero} (indices 0-{nonzero-1})")

    # Emit .asm file
    lines = []
    lines.append("* ============================================================")
    lines.append("* exptbl.asm — exp() lookup table for softmax")
    lines.append("* ============================================================")
    lines.append("* Generated by tables/gen_exptbl.py")
    lines.append("* 256 entries, Q8 format: EXPTBL[i] = round(exp(-i/32) * 256)")
    lines.append("* Covers x in [-7.97, 0]. Beyond that, exp() rounds to zero.")
    lines.append("* Total: 512 bytes (256 * 2)")
    lines.append("* ============================================================")
    lines.append("")
    lines.append("EXPTBL:")

    for row in range(32):
        idx = row * 8
        vals = [f"{tbl[idx+j]}" for j in range(8)]
        line = "                FDB     " + ",".join(vals)
        line += f"  ; [{idx}]-[{idx+7}]"
        lines.append(line)

    out = Path("tables") / "exptbl.asm"
    out.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {out} ({len(lines)} lines)")

    # Also emit raw binary for cross-check
    raw = bytearray()
    for v in tbl:
        raw += v.to_bytes(2, 'big')
    Path("tables/exptbl.bin").write_bytes(raw)
    print(f"wrote tables/exptbl.bin ({len(raw)} bytes)")

if __name__ == "__main__":
    main()
