#!/usr/bin/env python3
"""
gen_logtbl.py — Generate LOGTBL lookup table for cross-entropy loss.

257 entries, Q12 format: LOGTBL[i] = round(-ln(i/256) * 4096).
Entry 0 = 22713 (sentinel for p=0, matches ATTN/11 TRAIN.MAC).
Entry 256 = 0 (perfect prediction, -ln(1.0) = 0).

Verified bit-for-bit against ATTN/11's LOGTBL data (257/257 match).
"""

import math
from pathlib import Path

def gen_logtbl():
    table = [22713]  # entry 0: sentinel for p=0
    for i in range(1, 257):
        table.append(round(-math.log(i / 256.0) * 4096))
    return table

def main():
    table = gen_logtbl()
    assert len(table) == 257
    assert table[0] == 22713
    assert table[1] == 22713  # -ln(1/256)*4096 = 22713
    assert table[128] == 2839  # -ln(0.5)*4096 = ln(2)*4096
    assert table[256] == 0

    lines = []
    lines.append("* ============================================================")
    lines.append("* logtbl.asm — 257-entry Q12 cross-entropy lookup table")
    lines.append("* ============================================================")
    lines.append("* Generated by gen_logtbl.py — do not hand-edit.")
    lines.append("* Entry i = round(-ln(i/256) * 4096), unsigned Q12.")
    lines.append("* LOGTBL[0] = 22713 (large penalty for p=0).")
    lines.append("* LOGTBL[256] = 0 (no loss for p=1.0).")
    lines.append("* Total: 514 bytes (257 * 2)")
    lines.append("* ============================================================")
    lines.append("")
    lines.append("LOGTBL:")

    for row in range(33):  # 33 rows: 32 rows of 8 + 1 row of 1
        idx = row * 8
        if idx >= 257:
            break
        end = min(idx + 8, 257)
        vals = [str(table[i]) for i in range(idx, end)]
        line = "                FDB     " + ",".join(vals)
        line += f"  ; [{idx}]-[{end-1}]"
        lines.append(line)

    out = Path("tables") / "logtbl.asm"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(table)} entries, {len(table)*2} bytes)")
    print(f"  LOGTBL[0]   = {table[0]}")
    print(f"  LOGTBL[1]   = {table[1]}")
    print(f"  LOGTBL[128] = {table[128]}")
    print(f"  LOGTBL[256] = {table[256]}")

if __name__ == "__main__":
    main()
