#!/usr/bin/env python3
"""
CLOSS reference generator — cross-entropy loss test vectors.

Matches src/train.asm CLOSS exactly:
  For each position: sftmx(logits[i]) → p = probs[target[i]]
  If p >= 256: loss_i = 0. Else: loss_i = LOGTBL[p].
  Accumulate 32-bit unsigned. Average >>3 (hardcoded /8 for SEQ=8).

All tests use SEQ=8 to match the hardcoded >>3 averaging.
"""

import math
from pathlib import Path

# ---- EXPTBL + LOGTBL (must match tables/*.asm exactly) ----

EXPTBL = [max(0, int(math.exp(-i / 32.0) * 256.0 + 0.5)) for i in range(256)]

LOGTBL = [22713]  # entry 0: sentinel
for _i in range(1, 257):
    LOGTBL.append(round(-math.log(_i / 256.0) * 4096))

# ---- Primitives ----

def fxdiv_ref(a, b):
    if b == 0:
        return 0
    numerator = a * 256
    if (numerator >= 0 and b >= 0) or (numerator < 0 and b < 0):
        result = numerator // b
    else:
        result = -(abs(numerator) // abs(b))
    return max(-32768, min(32767, result))

def sftmx_ref(vec):
    n = len(vec)
    mx = max(vec)
    exps = []
    for v in vec:
        diff = mx - v
        idx = 255 if diff > 2040 else (diff >> 3)
        if idx > 255:
            idx = 255
        exps.append(EXPTBL[idx])
    s = sum(exps)
    if s == 0:
        return [0] * n
    return [fxdiv_ref(e, s) for e in exps]

def closs_ref(logits, targets, seq, voc):
    """Returns Q12 unsigned 16-bit loss (averaged >>3)."""
    acc = 0
    for i in range(seq):
        probs = sftmx_ref(logits[i])
        p = probs[targets[i]]
        if p >= 256:
            loss_i = 0
        else:
            loss_i = LOGTBL[p]
        acc = (acc + loss_i) & 0xFFFFFFFF
    result = acc >> 3
    assert result <= 65535, f"Loss {result} exceeds 16-bit"
    return result

# ---- Self-test ----

def self_test():
    assert LOGTBL[0] == 22713
    assert LOGTBL[256] == 0
    assert LOGTBL[128] == 2839
    assert len(LOGTBL) == 257
    assert EXPTBL[0] == 256
    assert len(EXPTBL) == 256

    assert sftmx_ref([128, 128]) == [128, 128]
    r = sftmx_ref([0] * 10)
    assert all(abs(v - 25) <= 1 for v in r), f"uniform sftmx: {r}"

    print("Self-test passed")

# ---- Test cases (all SEQ=8 VOC=10) ----

SEQ, VOC = 8, 10

def test_0():
    """CLOSS_UNIFORM: all logits zero → uniform softmax."""
    logits = [[0] * VOC for _ in range(SEQ)]
    targets = list(range(SEQ))  # [0,1,2,3,4,5,6,7]
    return ("CLOSS_UNIFORM", logits, targets)

def test_1():
    """CLOSS_PERFECT: dominant correct logit → p≈256 → loss≈0."""
    logits = []
    targets = list(range(SEQ))
    for i in range(SEQ):
        row = [0] * VOC
        row[targets[i]] = 4000  # large → softmax gives ~256
        logits.append(row)
    return ("CLOSS_PERFECT", logits, targets)

def test_2():
    """CLOSS_WRONG: dominant WRONG logit → p≈0 for correct class."""
    logits = []
    targets = list(range(SEQ))
    for i in range(SEQ):
        row = [0] * VOC
        wrong = (targets[i] + 1) % VOC
        row[wrong] = 4000  # wrong class dominates
        logits.append(row)
    return ("CLOSS_WRONG", logits, targets)

def test_3():
    """CLOSS_MIXED: varied logits, some correct some wrong."""
    logits = []
    targets = [3, 7, 1, 5, 0, 9, 4, 2]
    for i in range(SEQ):
        row = [(i * 7 + v * 3) % 400 - 200 for v in range(VOC)]
        logits.append(row)
    return ("CLOSS_MIXED", logits, targets)

def all_tests():
    return [test_0(), test_1(), test_2(), test_3()]

# ---- Emission ----

def emit_asm(path, test_data):
    lines = []
    lines.append("* ============================================================")
    lines.append("* closs_vectors.asm — test vectors for CLOSS harness")
    lines.append("* Generated by gen_closs_vectors.py — do not hand-edit.")
    lines.append("* All tests SEQ=8 VOC=10 (matching hardcoded >>3 averaging).")
    lines.append("* ============================================================")
    lines.append("")

    for idx, (name, logits, targets, expected) in enumerate(test_data):
        lines.append(f"* Test {idx}: {name}")
        lines.append(f"SEQ_{idx}          FDB  {SEQ}")
        lines.append(f"VOC_{idx}          FDB  {VOC}")
        lg_flat = [v for row in logits for v in row]
        lines.append(f"LOGITS_{idx}       FDB  {','.join(str(v) for v in lg_flat)}")
        lines.append(f"TARGETS_{idx}      FDB  {','.join(str(v) for v in targets)}")
        lines.append(f"EXPECT_{idx}       FDB  {expected}")
        lines.append("")

    Path(path).write_text("\n".join(lines) + "\n")

def emit_log(path, test_data):
    lines = []
    lines.append("CLOSS reference generator log")
    lines.append("=" * 60)
    lines.append("")
    for idx, (name, logits, targets, expected) in enumerate(test_data):
        lines.append(f"Test {idx}: {name}  SEQ={SEQ} VOC={VOC}")
        lines.append(f"  targets = {targets}")
        lines.append(f"  expected loss (Q12) = {expected}")
        acc = 0
        for i in range(SEQ):
            probs = sftmx_ref(logits[i])
            p = probs[targets[i]]
            loss_i = 0 if p >= 256 else LOGTBL[p]
            acc += loss_i
            lines.append(f"  pos {i}: target={targets[i]} p={p} "
                         f"loss_i={loss_i} acc={acc}")
        lines.append(f"  sum={acc} >>3={acc>>3}")
        lines.append("")
    Path(path).write_text("\n".join(lines) + "\n")

# ---- Main ----

def main():
    self_test()
    tests = all_tests()
    test_data = []
    for (name, logits, targets) in tests:
        expected = closs_ref(logits, targets, SEQ, VOC)
        test_data.append((name, logits, targets, expected))

    out_dir = Path("tables")
    out_dir.mkdir(exist_ok=True)
    emit_asm(out_dir / "closs_vectors.asm", test_data)
    emit_log(out_dir / "closs_vectors.log", test_data)

    print(f"\nwrote tables/closs_vectors.asm ({len(test_data)} tests)")
    print(f"wrote tables/closs_vectors.log")
    print("\nSummary:")
    for idx, (name, logits, targets, expected) in enumerate(test_data):
        print(f"  Test {idx} ({name}): expected Q12 loss = {expected}")

if __name__ == "__main__":
    main()
