* ============================================================
* proj_vectors.asm — test vectors for PROJ harness
* Generated by gen_proj_vectors.py — do not hand-edit.
* Per-product shift-accumulate semantics matching ATTN/11 VTMUL.
* Two-stage clamp per step: clamp shifted product, clamp running sum.
* WOUT layout: [d_model][vocab] row-major.
* Element Wout[d][v] at offset (d*VOC + v)*2 bytes from WOUT base.
* ============================================================

* Test 0: PROJ_SINGLE
SEQ_0          FDB  1
DIM_0          FDB  4
VOC_0          FDB  3
CNT_0          FDB  3                    ; SEQ * VOC (output verify)
Y_CNT_0        FDB  4                    ; SEQ * DIM (Y load)
WOUT_CNT_0     FDB  12                    ; DIM * VOC (WOUT load)
Y_0            FDB  100,200,300,400
WOUT_0         FDB  10,20,30,40,50,60,70,80,90,100,110,120
EXPECT_0       FDB  272,310,349

* Test 1: PROJ_SEQ4
SEQ_1          FDB  4
DIM_1          FDB  8
VOC_1          FDB  5
CNT_1          FDB  20                    ; SEQ * VOC (output verify)
Y_CNT_1        FDB  32                    ; SEQ * DIM (Y load)
WOUT_CNT_1     FDB  40                    ; DIM * VOC (WOUT load)
Y_1            FDB  1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,21,22,23,24,25,26,27,28,31,32,33,34,35,36,37,38
WOUT_1         FDB  2,3,4,5,6,5,6,7,8,9,8,9,10,11,12,11,12,13,14,15,14,15,16,17,18,17,18,19,20,21,20,21,22,23,24,23,24,25,26,27
EXPECT_1       FDB  0,0,0,0,0,3,3,3,3,4,7,7,7,8,9,10,12,12,13,14

* Test 2: PROJ_FULL
* Y pattern: Y[i][d] = (i*7 + d*3) %% 200 - 100  (range [-100, 99])
* Wout pattern: Wout[d][v] = (d*5 + v*2) %% 100 - 50  (range [-50, 49])
SEQ_2          FDB  8
DIM_2          FDB  16
VOC_2          FDB  10
CNT_2          FDB  80                    ; SEQ * VOC (output verify)
Y_CNT_2        FDB  128                    ; SEQ * DIM (Y load)
WOUT_CNT_2     FDB  160                    ; DIM * VOC (WOUT load)
Y_2            FDB  -100,-97,-94,-91,-88,-85,-82,-79,-76,-73,-70,-67,-64,-61,-58,-55,-93,-90,-87,-84,-81,-78,-75,-72,-69,-66,-63,-60,-57,-54,-51,-48,-86,-83,-80,-77,-74,-71,-68,-65,-62,-59,-56,-53,-50,-47,-44,-41,-79,-76,-73,-70,-67,-64,-61,-58,-55,-52,-49,-46,-43,-40,-37,-34,-72,-69,-66,-63,-60,-57,-54,-51,-48,-45,-42,-39,-36,-33,-30,-27,-65,-62,-59,-56,-53,-50,-47,-44,-41,-38,-35,-32,-29,-26,-23,-20,-58,-55,-52,-49,-46,-43,-40,-37,-34,-31,-28,-25,-22,-19,-16,-13,-51,-48,-45,-42,-39,-36,-33,-30,-27,-24,-21,-18,-15,-12,-9,-6
WOUT_2         FDB  -50,-48,-46,-44,-42,-40,-38,-36,-34,-32,-45,-43,-41,-39,-37,-35,-33,-31,-29,-27,-40,-38,-36,-34,-32,-30,-28,-26,-24,-22,-35,-33,-31,-29,-27,-25,-23,-21,-19,-17,-30,-28,-26,-24,-22,-20,-18,-16,-14,-12,-25,-23,-21,-19,-17,-15,-13,-11,-9,-7,-20,-18,-16,-14,-12,-10,-8,-6,-4,-2,-15,-13,-11,-9,-7,-5,-3,-1,1,3,-10,-8,-6,-4,-2,0,2,4,6,8,-5,-3,-1,1,3,5,7,9,11,13,0,2,4,6,8,10,12,14,16,18,5,7,9,11,13,15,17,19,21,23,10,12,14,16,18,20,22,24,26,28,15,17,19,21,23,25,27,29,31,33,20,22,24,26,28,30,32,34,36,38,25,27,29,31,33,35,37,39,41,43
EXPECT_2       FDB  73,63,52,45,33,26,15,6,-7,-12,67,58,50,40,31,24,15,4,-1,-13,61,52,47,36,31,22,14,8,-2,-9,58,47,44,34,26,22,12,8,-2,-7,52,44,40,31,26,21,13,9,1,-4,45,41,33,28,23,19,13,9,2,-2,41,34,30,26,22,19,15,8,2,0,35,32,29,24,20,17,12,9,6,1

* Test 3: PROJ_SAT_POS
* First saturating step: i=0 v=0 d=0 product=900000000 shifted=3515625 stage1=32767 (stage1 clamp)
SEQ_3          FDB  1
DIM_3          FDB  4
VOC_3          FDB  3
CNT_3          FDB  3                    ; SEQ * VOC (output verify)
Y_CNT_3        FDB  4                    ; SEQ * DIM (Y load)
WOUT_CNT_3     FDB  12                    ; DIM * VOC (WOUT load)
Y_3            FDB  30000,30000,30000,30000
WOUT_3         FDB  30000,0,0,30000,0,0,30000,0,0,30000,0,0
EXPECT_3       FDB  32767,0,0

* Test 4: PROJ_SAT_NEG
* First saturating step: i=0 v=0 d=0 product=-900000000 shifted=-3515625 stage1=-32768 (stage1 clamp)
SEQ_4          FDB  1
DIM_4          FDB  4
VOC_4          FDB  3
CNT_4          FDB  3                    ; SEQ * VOC (output verify)
Y_CNT_4        FDB  4                    ; SEQ * DIM (Y load)
WOUT_CNT_4     FDB  12                    ; DIM * VOC (WOUT load)
Y_4            FDB  -30000,-30000,-30000,-30000
WOUT_4         FDB  30000,0,0,30000,0,0,30000,0,0,30000,0,0
EXPECT_4       FDB  -32768,0,0

