* ============================================================
* updat_vectors.asm - UPDAT routines test vectors
* Generated by gen_updat_vectors.py - do not hand-edit.
* ============================================================

* Test 0: UP_T0_WUPDT_BASIC  mode=wupdt
CNT_0         FDB  4
SHF_0         FDB  1
WHI_0         FDB  0,0,0,0
WLO_0         FDB  1000,2000,-500,-1000
GRAD_0        FDB  100,-200,300,-50
EXP_WHI_0     FDB  0,0,0,0
EXP_WLO_0     FDB  900,2200,-800,-950
EXP_GRAD_0    FDB  0,0,0,0

* Test 1: UP_T1_WUPDT_SHIFTED  mode=wupdt
CNT_1         FDB  4
SHF_1         FDB  4
WHI_1         FDB  0,5,-1,0
WLO_1         FDB  10000,0,-32768,-1
GRAD_1        FDB  8000,800,80,-8000
EXP_WHI_1     FDB  0,4,-1,1
EXP_WLO_1     FDB  9000,-100,32758,999
EXP_GRAD_1    FDB  0,0,0,0

* Test 2: UP_T2_CVT16_BASIC  mode=cvt16
CNT_2         FDB  4
WHI_2         FDB  18,0,-1,0
WLO_2         FDB  13312,32768,0,0
EXP_Q8_2      FDB  4660,128,-256,0

* Test 3: UP_T3_INITW_RAND  mode=initw
CNT_3         FDB  8
SEED_3        FDB  887
EXP_WHI_3     FDB  0,0,-1,-1,0,-1,0,0
EXP_WLO_3     FDB  7168,25856,-24064,-7424,30720,-3840,7680,3840
EXP_Q8_3      FDB  28,101,-94,-29,120,-15,30,15

* Test 4: UP_T4_WUPDT_CARRY  mode=wupdt
CNT_4         FDB  4
SHF_4         FDB  1
WHI_4         FDB  0,0,1,-1
WLO_4         FDB  32767,-1,0,0
GRAD_4        FDB  -100,-1,1,1
EXP_WHI_4     FDB  0,1,0,-2
EXP_WLO_4     FDB  -32669,0,-1,-1
EXP_GRAD_4    FDB  0,0,0,0

