* ============================================================
* vsadd_vectors.asm - test vectors for VSADD harness
* Generated by gen_vsadd_vectors.py - do not hand-edit
* Two-stage clamp semantics (matches VSADD, not MATOP)
* ============================================================

* Test 0: VSADD_ZERO_SCL
DST_0_INIT     FDB 100,200,300,400
SRC_0          FDB 1000,2000,3000,4000
SCL_0          FDB 0
LEN_0          FDB 4
EXPECT_0       FDB 100,200,300,400

* Test 1: VSADD_UNIT_SCL
DST_1_INIT     FDB 100,200,-300,400
SRC_1          FDB 50,60,70,-80
SCL_1          FDB 256
LEN_1          FDB 4
EXPECT_1       FDB 150,260,-230,320

* Test 2: VSADD_POS_NOSAT
DST_2_INIT     FDB 100,200,300,400
SRC_2          FDB 50,60,70,80
SCL_2          FDB 128
LEN_2          FDB 4
EXPECT_2       FDB 125,230,335,440

* Test 3: VSADD_NEG_NOSAT
DST_3_INIT     FDB 1000,-1000,500,-500
SRC_3          FDB 100,-100,200,-200
SCL_3          FDB -128
LEN_3          FDB 4
EXPECT_3       FDB 950,-950,400,-400

* Test 4: VSADD_PRODUCT_SAT
*   DIVERGENCE from single-clamp semantics:
*   two-stage (ours):  12767
*   single-clamp:      32767
DST_4_INIT     FDB -20000
SRC_4          FDB 20000
SCL_4          FDB 20000
LEN_4          FDB 1
EXPECT_4       FDB 12767

* Test 5: VSADD_SUM_SAT
DST_5_INIT     FDB 30000
SRC_5          FDB 10000
SCL_5          FDB 200
LEN_5          FDB 1
EXPECT_5       FDB 32767

* Test 6: VSADD_BOTH_SAT
DST_6_INIT     FDB 20000
SRC_6          FDB 20000
SCL_6          FDB 20000
LEN_6          FDB 1
EXPECT_6       FDB 32767

* Test 7: VSADD_LEN0
DST_7_INIT     FDB 1234,5678,-4321,9999
SRC_7          FDB 100,200,300,400
SCL_7          FDB 128
LEN_7          FDB 0
EXPECT_7       FDB 1234,5678,-4321,9999  ; same as DST_7_INIT (no-op)

* Test 8: VSADD_LEN1
DST_8_INIT     FDB 100,9999
SRC_8          FDB 200,0
SCL_8          FDB 128
LEN_8          FDB 1
EXPECT_8       FDB 200

* Test 9: VSADD_LEN16_MIXED
DST_9_INIT     FDB 100,-200,300,-400,500,-600,700,-800,20000,-20000,15000,-15000,100,200,300,400
SRC_9          FDB 1000,2000,-1500,2500,-3000,3500,-4000,4500,20000,20000,-20000,-20000,0,100,-100,50
SCL_9          FDB 200
LEN_9          FDB 16
EXPECT_9       FDB 881,1362,-872,1553,-1844,2134,-2425,2715,32767,-4375,-625,-30625,100,278,221,439

