* ============================================================
* tables.asm — Lookup table binary includes
* ============================================================
* Dependencies: equates.inc
* Exports: EXPTBL, LOGTBL
* ============================================================
*
* TODO: implement in subsequent turn
*
* Will contain:
*   EXPTBL  — 256 bytes, Q8 exp(-i/32) for i=0..255
*             Generated by tables/gen_exptbl.py → tables/exptbl.bin
*             Used by SOFTMAX_Q8 in actfn.asm
*
*   LOGTBL  — 514 bytes (257 × 2), Q12 -ln(x/256)*4096
*             Generated by tables/gen_logtbl.py → tables/logtbl.bin
*             Used by CROSS_ENTROPY_Q15 in actfn.asm
*
* Binary files are .incbin'd at assembly time.
*

                INCLUDE equates.inc

* Stub — flat binary, no SECTION needed

* Stub — .incbin directives will go here once table generators run
* EXPTBL  INCBIN  "tables/exptbl.bin"
* LOGTBL  INCBIN  "tables/logtbl.bin"


